# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "db/**/*"
    - "Rakefile"
    - "*.gemspec"
    - "**/node_modules/**/*"

Rails:
  Enabled: true


Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LineLength:
  Max: 130

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled: false


Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 45

Metrics/PerceivedComplexity:
  Max: 10


Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
